language: java

jdk:
  - openjdk17
  - openjdk16
  - openjdk11
  - openjdk8

script:
  - ./mvnw clean verify
  - ./mvnw clean verify -Dspring.version=$(./travis/get_latest_version.sh spring-core 5.2) -Dspring-batch.version=$(./travis/get_latest_version.sh batch/spring-batch-core 4.2)
  - ./mvnw clean verify -Dspring.version=$(./travis/get_latest_version.sh spring-core 5.1) -Dspring-batch.version=$(./travis/get_latest_version.sh batch/spring-batch-core 4.1)
